### ISSUE TITLE
Create Website Footer

### ISSUE THREAD

**Issue by JohanPeraldi** [JohanPeraldi/dark-debris#4]
# Implement Site Footer

## Description
Add a footer section with relevant links and information.

## Tasks

- [ ] Create `Footer.astro` component
- [ ] Add social media links
- [ ] Include copyright information
- [ ] Add any additional relevant links (portfolio, contact, cv)
- [ ] Style footer to match website theme

## Acceptance Criteria

- Footer is visually consistent with site design
- Social media links are functional
- Responsive layout
- Copyright information is current
- Proper spacing and alignment
