### ISSUE TITLE
Implement Dark/Light Theme Switching

### ISSUE THREAD

**Issue by JohanPeraldi** [JohanPeraldi/dark-debris#6]
# Add Theme Switching Functionality

## Description
Implement a theme switching system that allows users to toggle between dark and light modes, with system preference detection and theme persistence.

## Technical Background
Current implementation uses CSS variables in global.css with a dark theme base. Need to expand this to support dynamic theme switching.

## Tasks

- [ ] Create theme configuration
- [ ] Define light theme color palette in global.css
- [ ] Reorganise existing dark theme variables
- [ ] Create semantic color variables for both themes
- [ ] Implement theme switching logic
- [ ] Create `ThemeProvider` component
- [ ] Add theme toggle button component
- [ ] Implement local storage for theme persistence
- [ ] Add system theme preference detection
- [ ] Update existing components
- [ ] Audit and update all color usages to use theme variables
- [ ] Ensure proper contrast ratios in both themes
- [ ] Add transition animations for theme switches
- [ ] UI/UX Implementation
- [ ] Design and implement theme toggle button
- [ ] Add appropriate icons for sun/moon
- [ ] Implement smooth transition animations
- [ ] Add keyboard accessibility for theme switching

## Color Variables to Add
```css
:root[data-theme="light"] {
  --site-bg: #ffffff;
  --color-primary-100: #...; /* Light theme equivalents */
  --color-primary-200: #...;
  --color-primary-300: #...;
  --color-primary-400: #...;
  /* Add other light theme variables */
}

/* Keep existing dark theme variables */
:root[data-theme="dark"] {
  /* Current variables from global.css */
}
```

## Acceptance Criteria

- Theme toggle is accessible via keyboard and screen readers
- Theme preference persists between page reloads
- System preference is respected on first visit
- All components maintain proper contrast ratios in both themes
- Smooth transitions between themes (no jarring changes)
- All text remains readable in both themes
- Icons and images are appropriately adjusted for each theme
- Theme switch works across all pages and components
- No UI elements break during theme transitions

## Implementation Notes

- Use CSS custom properties for theme values
- Implement theme switch using prefers-color-scheme media query
- Store theme preference in localStorage
- Add appropriate ARIA labels for accessibility
- Consider using CSS transitions for smooth theme switching

## Testing Requirements

- Test across different browsers
- Verify system preference detection
- Check persistence across page reloads
- Verify all components in both themes
- Test keyboard accessibility
- Verify contrast ratios meet WCAG guidelines

## Resources

- Current color scheme in global.css
- Tailwind CSS dark mode documentation
- WCAG contrast guidelines
